# Generated by Django 2.2.1 on 2019-05-23 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('sigla', models.CharField(max_length=5)),
                ('carga_horaria', models.IntegerField()),
                ('semestres', models.SmallIntegerField()),
                ('ementa', models.TextField()),
            ],
        ),
    ]
